default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dms_development

test:
  <<: *default
  database: dms_test

production:
  <<: *default
  database: dms_production
  username: dms
  password: <%= ENV['DMS_DATABASE_PASSWORD'] %>