default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: siten_development

test:
  <<: *default
  database: siten_test

production:
  <<: *default
  database: siten_production
  username: siten
  password: <%= ENV['SITEN_DATABASE_PASSWORD'] %>